### ISSUE TITLE
NameError: name 'fused' is not defined

### ISSUE THREAD

**Issue by netrunner-exe** [truongvu2000nd/AFS#1]
```
StyleGAN2: Optimized CUDA op FusedLeakyReLU not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op UpFirDn2d not available, using native PyTorch fallback.
Load e4e model: ./weights/e4e_ffhq_encode.pt
Loading e4e over the pSp framework from checkpoint: ./weights/e4e_ffhq_encode.pt
<All keys matched successfully>
Load style extraction model: ./weights/style_extraction.pth
<All keys matched successfully>
Load generator: ./weights/stylegan2-ffhq-config-f.pt
Load stylegan2 model from weights/stylegan2-ffhq-config-f.pt
Traceback (most recent call last):
  File "inference.py", line 22, in <module>
    afs = AFS(ckpt_e4e=args.e4e_path,
  File "/content/AFS/models/afs.py", line 97, in __init__
    self.generator.load_model(ckpt_stylegan)
  File "/content/AFS/models/stylegan2/stylegan2.py", line 70, in load_model
    self.latent_avg = self.model.mean_latent(4096)
  File "/content/AFS/models/stylegan2/model.py", line 488, in mean_latent
    latent = self.style(latent_in).mean(0, keepdim=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/AFS/models/stylegan2/model.py", line 153, in forward
    out = fused_leaky_relu(out, self.bias * self.lr_mul)
  File "/content/AFS/models/stylegan2/op/fused_act.py", line 131, in fused_leaky_relu
    return FusedLeakyReLUFunction.apply(
  File "/content/AFS/models/stylegan2/op/fused_act.py", line 78, in forward
    out = fused.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
NameError: name 'fused' is not defined
```

**Comment by netgeek888** [comment]
I'm running into the same issue. @netrunner-exe, how does installing ninja solve this? It seems like we need to build fused, but there are no instructions on how to do that. Thanks.

**Comment by truong-v** [comment]
> I'm running into the same issue. @netrunner-exe, how does installing ninja solve this? It seems like we need to build fused, but there are no instructions on how to do that. Thanks.

You just install it with pip `pip install ninja`. You can read more about the JIT Compiling Extensions from the Pytorch tutorial https://pytorch.org/tutorials/advanced/cpp_extension.html#jit-compiling-extensions

**Comment by netgeek888** [comment]
@truongvu2000nd, thanks for the tip. I installed ninja but I'm still getting the same error when I run the inference.py script. What other steps am I missing? Thanks.

**Comment by truong-v** [comment]
I think you might get the error if you run on a cpu-only machine. If it's not the case, could you please remove the try catch logic in https://github.com/truongvu2000nd/AFS/blob/main/models/stylegan2/op/fused_act.py#L19-L23 and rerun to get the full error traceback?

**Comment by netgeek888** [comment]
I'm running on an Ubuntu machine with a CUDA enabled GPU. I removed the try...catch block as you suggested and ran the inference again. Here is the error message.


```
(afs) netgeek@DevBox:~/Developer/packages/AFS$ python inference.py     --src_img demo/source.jpg     --tgt_img demo/target.jpg     --save_dir demo/output2.jpg
Traceback (most recent call last):
  File "/home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/home/netgeek/anaconda3/envs/afs/lib/python3.6/subprocess.py", line 438, in run 
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "inference.py", line 4, in <module>
    from models.afs import AFS 
  File "/home/netgeek/Developer/packages/AFS/models/__init__.py", line 1, in <module>
    from .afs import AFS 
  File "/home/netgeek/Developer/packages/AFS/models/afs.py", line 7, in <module>
    from .stylegan2.stylegan2 import StyleGAN2Generator as Generator
  File "/home/netgeek/Developer/packages/AFS/models/stylegan2/__init__.py", line 1, in <module>
    from .stylegan2 import StyleGAN2Generator
  File "/home/netgeek/Developer/packages/AFS/models/stylegan2/stylegan2.py", line 20, in <module>
    from .model import Generator as StyleGAN2Model
  File "/home/netgeek/Developer/packages/AFS/models/stylegan2/model.py", line 7, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/netgeek/Developer/packages/AFS/models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/netgeek/Developer/packages/AFS/models/stylegan2/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 980, in load
    keep_intermediates=keep_intermediates)
  File "/home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1185, in _jit_compile
    with_cuda=with_cuda)
  File "/home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1283, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "/home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /home/netgeek/anaconda3/envs/afs/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/TH -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/THC -isystem /home/netgeek/anaconda3/envs/afs/include -isystem /home/netgeek/anaconda3/envs/afs/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/netgeek/Developer/packages/AFS/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o
/home/netgeek/anaconda3/envs/afs/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/TH -isystem /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/THC -isystem /home/netgeek/anaconda3/envs/afs/include -isystem /home/netgeek/anaconda3/envs/afs/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/netgeek/Developer/packages/AFS/models/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
In file included from /home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAApplyUtils.cuh:6:0,
                 from /home/netgeek/Developer/packages/AFS/models/stylegan2/op/fused_bias_act_kernel.cu:11:
/home/netgeek/anaconda3/envs/afs/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
 #include <cusolverDn.h>
          ^~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

```

I have CUDA toolkit 11.0 and 11.2 installed on the machine but the compiler doesn't seem to be finding it. How can I fix this?

Thanks.

**Comment by truong-v** [comment]
Which pytorch version do you use? Mine is pytorch 1.9.0 + CUDA 11.1

**Comment by netgeek888** [comment]
I'm using Anaconda to install the packages. This is what it installed:

```
Name                    Version                   Build  Channel
pytorch                   1.7.0           py3.6_cuda11.0.221_cudnn8.0.3_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch

```
Pytorch 1.9.0 doesn't seem to be available among the Anaconda packages. There are newer versions like Pytorch 1.12, but doesn't match your environment either. Did you manually install your packages?

If you can specify the specific OS and packages you used and how you installed them, I can try to replicate your set up. Thanks.

**Comment by truong-v** [comment]
You should follow the official instruction to install pytorch: https://pytorch.org/get-started/previous-versions/#osx-12
My OS is Ubuntu 18.04.4 LTS

**Comment by zhqlyqy** [comment]
> 我正在使用 Anaconda 安装软件包。这是它安装的：
> 
> ```
> Name                    Version                   Build  Channel
> pytorch                   1.7.0           py3.6_cuda11.0.221_cudnn8.0.3_0    pytorch
> pytorch-cuda              11.6                 h867d48c_1    pytorch
> ```
> 
> Pytorch 1.9.0 似乎在 Anaconda 软件包中不可用。有更新的版本，如 Pytorch 1.12，但也不符合您的环境。您是不是手动安装了软件包？
> 
> 如果您可以指定您使用的特定操作系统和软件包以及安装它们的方式，我可以试试复制您的设置。谢谢。

你解决了这个问题吗？

**Comment by americanexplorer13** [comment]
> Which pytorch version do you use? Mine is pytorch 1.9.0 + CUDA 11.1

Could you please update requirements for you code base? Thank you!
